spring.application.name=nino_backend_spring
spring.datasource.url=jdbc:postgresql://localhost:5432/WslNinoLocal
spring.datasource.username=TifosiAdmin
spring.datasource.password=TifosiLocal102938!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret-key=znndqjSw4IsSFhxEuC+siX1JugG/KEuZz/Pf2IdDobL41a4vGHZIc2aE0249uqUGPe46IDfBGZUhojAOyPYWbg==
# 1h in millisecond
spring.security.jwt.expiration-time=3600000
logging.level.org.springframework.security=DEBUG
logging.level.ai.tifosi.nino_backend_spring=DEBUG